name: Bug Report
description: Create a bug report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue:

        - Do a search of existing issues.
        - Pull the latest updates from this repository's `dev` branch.

        If you need help with your own project, you can start a discussion in the [Q&A Section](https://github.com/weaponsforge/fumadocs-template/discussions/categories/q-a).

  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, or a link to the reproducible repository.
      placeholder: |
        1. Start the application in development (next dev)
        2. Click X
        3. Y will happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: 'Following the steps from the previous section, I expected A to happen, but I observed B instead'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `next info` in the root directory of your project and paste the results.
      render: bash
      placeholder: |
        Operating System:
          Platform: linux
          Arch: x64
          Version: #1 SMP Tue Nov 5 00:21:55 UTC 2024
        Binaries:
          Node: 24.11.0
          npm: 11.6.1
          Yarn: 1.22.22
          pnpm: N/A
        Relevant Packages:
          next: 15.5.9
          eslint-config-next: N/A
          react: 19.2.1
          react-dom: 19.2.1
          typescript: 5.9.3
        Next.js Config:
          output: standalone

    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Not sure'
        - 'MDX (Markdown) Content'
        - 'React Component'
        - 'Fumadocs UI'
        - 'CSS Styling'
        - 'Authentication'
        - 'Others'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
      placeholder: |
        I tested my reproduction against different NextJS releases, and the first one that introduced the bug was "v16", since reverting to "v15" works.
